[엄재홍] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/31-westagram-backend-3-team pull request #10
Opened 2022-03-21 06:51 UTC by youbeemuhwan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)

		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-21 09:38 UTC, bigfanoftim requested changes

2022-03-21 09:38 UTC, bigfanoftim commented on students/jaehong/users/urls.py
> +from .views import *
필요한 모듈만 import 해주세요!

2022-03-21 09:38 UTC, bigfanoftim commented on students/jaehong/users/views.py
> +            if User.objects.filter(email=email).exists() : # 기존 가입한 회원의 이메일과 가입할려는 사람의 이메일이 같을시 에러 반환
이 정도 기능에서는 주석을 굳이 달아주지 않아도 될 것 같습니다!
```suggestion
            if User.objects.filter(email=email).exists():
```

2022-03-21 09:38 UTC, bigfanoftim commented on students/jaehong/users/views.py
> +            phone_number = data["phone_number"]
가독성을 위해 `=` 혹은 `:`를 기준으로 정렬해주세요!

```python
name     = models.CharField(...)
email    = models.CharField(...)
password = models.CharField(...)
```

2022-03-21 09:38 UTC, bigfanoftim commented on students/jaehong/users/views.py
> +
가독성을 위해 `=` 혹은 `:`를 기준으로 정렬해주세요!

```python
name     = models.CharField(...)
email    = models.CharField(...)
password = models.CharField(...)
```
```suggestion
```

2022-03-22 01:33 UTC, kyeongraekim requested changes

2022-03-22 01:33 UTC, kyeongraekim commented on students/jaehong/users/views.py
> +            regex_password = "^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@$!%*#?&])[A-Za-z\d$@$!%*#?&]{8,}$"
정규표현식은 상수 데이터임으로 변수명은 대문자로 수정해주세요!~

2022-03-22 03:50 UTC, bigfanoftim approved these changes
LGTM 👍

2022-03-22 03:50 UTC, merged