[이강호] Mission 5: 회원가입 비밀번호 암호화 적용
wecode-bootcamp-korea/31-westagram-backend-3-team pull request #15
Opened 2022-03-22 08:41 UTC by gleehave

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 회원가입, 로그인 비밀번호 암호화
		 
## 수정 사항들 자세한 내용
- pip install bcrypt 설치 (requirement.txt 업데이트 완료)
- 회원가입 시, 패스워드 암호화하여 데이터베이스에 저장
- 로그인 시, 암호화된 상태에서 데이터이스에 저장된 패스워드와 체크
<img width="1420" alt="스크린샷 2022-03-22 오후 5 39 59" src="https://user-images.githubusercontent.com/91510831/159440935-c206c487-bc9e-4066-9faa-6e2028c91c30.png">

## 기타 질문 및 특이 사항
- 특이사항 없습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-03-22 10:47 UTC, youbeemuhwan commented on students/gangho/users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
혹시 password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8') 
이런 식으로 굳이 hashed_password를 따로 지정하지 않아도 되지 않나요?

2022-03-22 11:09 UTC, gleehave commented on students/gangho/users/views.py
> +            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')
중복되서 사용하기 때문에 hashed_password 변수를 선언해서 사용하였습니다!

2022-03-24 07:16 UTC, bigfanoftim requested changes

2022-03-24 07:16 UTC, bigfanoftim commented on students/gangho/requirements.txt
>  sqlparse==0.4.2
특정 패키지를 설치하면 자동으로 같이 설치되는 패키지들도 존재합니다.
따라서 아래와 같이 직접 설치한 특정 패키지들의 정보만 저장해주세요.
```python
# my_settings.py
bcrypt==3.2.0
Django==4.0.3
django-cors-headers==3.11.0
mysqlclient==2.1.0
PyJWT==2.3.0
```

2022-03-24 07:16 UTC, bigfanoftim commented on students/gangho/users/views.py
> +from my_settings import SECRET_KEY, ALGORITHM
```python
# views.py

from my_settings import ALGORITHM, SECRET_KEY
```

`ALGORITHM`, `SECRET_KEY`와 같은 환경변수를 my_settings.py 파일로 관리하고 있습니다. my_settings.py 파일은 환경변수 관리로서의 역할만 하는 파일로서 views.py 또는 models.py에서 직접 import해서 사용하시면 views.py 파일이 my_settings.py 파일에 의존성이 생기게 됩니다.

만약에 환경변수 관리를 my_settings.py가 아니라 아래와 같이 다른 방법으로 관리하게 되면 views.py에 코드도 전부 수정해야되는 것이죠.

```python
# settings.py

DATABASES = {
    ..
    "PASSWORD" : os.environ.get("DB_PASSWORD")
}
```

그러므로 my_settings.py에서 환경변수를 import해서 사용하실 때에는 지금처럼 `from my_settings import ALGORITHM, SECRET_KEY` 방법이 아니라 `from django.conf import settings`를 사용해서 환경변수를 불러와서 사용해주세요.

2022-03-24 07:16 UTC, bigfanoftim commented on students/gangho/users/views.py
> +            user_in_database = User.objects.get(email=email)
`user`는 그냥 유저일 뿐입니다. 변수명에 상황을 설명할 필요는 없어보입니다!
```suggestion
            user = User.objects.get(email=email)
```

2022-03-24 07:16 UTC, bigfanoftim commented on students/gangho/users/views.py
> +            user_in_database = User.objects.get(email=email)
`user = User.objects.get(email = email)` 에서 에러가 발생했을 경우에 except문에서 에러를 잡아줄 수 있도록 수정해주세요.

2022-03-24 08:08 UTC, gleehave commented on students/gangho/requirements.txt
>  sqlparse==0.4.2
requirement.txt 에 직접 설치한 특정 패키지 정보만 기입하여 수정하였습니다.

2022-03-24 08:09 UTC, gleehave commented on students/gangho/users/views.py
> +from my_settings import SECRET_KEY, ALGORITHM
환경 변수사용을 위해 from django.conf import settings 로 수정하였습니다.
해당 환경변수는 Mission 6에서 사용하겠습니다!

2022-03-24 08:11 UTC, gleehave commented on students/gangho/users/views.py
> +            user_in_database = User.objects.get(email=email)
user_in_database -> user 로 변수명 수정하였습니다. 
또한, user가 db에 없을 경우를 위해, User.DoesNotExist 로 예외처리 하였습니다.

2022-09-04 13:00 UTC, closed without merging